---
- hosts: all                            # Указываем что на все хрсты будет устанавливаться
  become: true                          # becomme или -b  означает что будет установка с повышенными правами (очень важно)
  tasks:                                # Добавляем зазачи для нашего playbook
      - name: Install aptitude
        apt:                                     #Здесь мы используеv apt встроенный модуль Ansible
          name: aptitude                         #  инструмент для взаимодействия с менеджером пакетов Linux и установки необходимых системных пакетов (Не обязательно)
          state: latest                          # Последняя версия
          update_cache: true                     # Обновление кеша после утановки (необязательный параметр)

      - name: Install required system packages
        apt:
          pkg:                                   # Добавляем необходимые программы (пакеты для работы с сертификатами ) для работы с Docker (много из этого уже установлено по умолчанию
            - apt-transport-https
            - ca-certificates
            - curl
            - software-properties-common
            - python3-pip
            - virtualenv
            - python3-setuptools
            - lsb-release
            - gitlab-runner              
            
              
          state: latest
          update_cache: true
      - name: install heroku cli via kubectl
        command: snap install kubectl --classic

      - name: install heroku cli via helm
        command: snap install helm --classic


      - name: Add Docker GPG apt Key             # Для проверки загрузки добавляется ключ Docker GPG, официальный репозиторий добавляется в качестве нового источника пакета, и Docker будет установлен
        apt_key:                                 # Встроенный модуль builtin.apt_key https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html#ansible-collections-ansible-builtin-apt-key-module
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

      - name: Add Docker Repository
        apt_repository:                           # модуль для добавления репозитория builtin.apt_repository
          repo: deb https://download.docker.com/linux/ubuntu focal stable
          state: present

      - name: Update apt and install docker-ce    # Установка самого Docker
        apt:
          name: docker-ce
          state: latest
          update_cache: true


